name: TourGuide CI - Push to Dev (unit tests only)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Copy local JARs to local Maven repository
        run: |
          mkdir -p ~/.m2/repository/gpsUtil/gpsUtil/1.0.0
          cp ./TourGuide/libs/gpsUtil.jar ~/.m2/repository/gpsUtil/gpsUtil/1.0.0/gpsUtil-1.0.0.jar
          
          mkdir -p ~/.m2/repository/tripPricer/tripPricer/1.0.0
          cp ./TourGuide/libs/TripPricer.jar ~/.m2/repository/tripPricer/tripPricer/1.0.0/tripPricer-1.0.0.jar
          
          mkdir -p ~/.m2/repository/rewardCentral/rewardCentral/1.0.0
          cp ./TourGuide/libs/RewardCentral.jar ~/.m2/repository/rewardCentral/rewardCentral/1.0.0/rewardCentral-1.0.0.jar


      - name: Build and Test (unit)
        run: mvn -B test --file TourGuide/pom.xml