name: CI/CD - UNIT TESTS & ARTIFACTS (PR main)

on:
  pull_request:
    branches: [main]

env:
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/tourguide

jobs:
  build-test-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install local JARs to local Maven repository
        run: |
          mvn install:install-file -Dfile=./TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=./TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=./TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      ######################## BUILDS ########################

      - name: Build, Test & Generate JaCoCo Coverage Report
        run: mvn -B verify --file TourGuide/pom.xml

      # temporary Docker image for scanning

      - name: Build Docker image for security scanning
        uses: docker/build-push-action@v6
        with:
          context: ./TourGuide
          file: ./TourGuide/Dockerfile
          push: false
          load: true
          tags: tourguide:security-scan

      ######################## SCANS ########################

      # Trivy scan for Docker image vulnerabilities (informative only)

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        id: trivy-scan
        with:
          image-ref: 'tourguide:security-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
        continue-on-error: true

      ######################## UPLOADS ########################

      # Trivy scan results

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

      # .jar file

      - name: Upload Application JAR
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-application
          path: TourGuide/target/*.jar
          if-no-files-found: error

      # Jacoco Report

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: TourGuide/target/site/jacoco-ut/

      # JavaDocs

      - name: Generate JavaDocs
        run: mvn javadoc:javadoc --file TourGuide/pom.xml

      - name: Upload JavaDocs
        uses: actions/upload-artifact@v4
        with:
          name: javadocs
          path: TourGuide/target/site/apidocs/

      # GitHub Pages

      - name: Prepare content GitHub Pages
        run: |
          mkdir -p gh-pages-build
          cp -r TourGuide/target/site/jacoco-ut gh-pages-build/jacoco
          cp -r TourGuide/target/site/apidocs gh-pages-build/javadocs

      - name: Deploy JavaDocs, JaCoCo, OWASP to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-build